### PR TITLE
Update for docutils 0.19

### PR DESCRIPTION
**Pull request by codeThatThinks**
ErrorString and SafeString are deprecated and have been removed in docutils 0.19. This PR replaces `ErrorString` with `io.error_string` and `SafeString` with Python's builtin `str()`.

See [docutils:HISTORY.txt](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/HISTORY.txt) and [docutils:utils/error_reporting.py](https://sourceforge.net/p/docutils/code/HEAD/tree/tags/docutils-0.19/docutils/utils/error_reporting.py) for more information.

### CODE REVIEW

**Comment by CrossNox** [comment]
Thanks for the PR! Seems straighforward, but I will look into it later tonight.  
My concern is that `python2.7` seems to be incompatible with the latest docutils versions, so I'll run the full tests suite and check.

**Comment by CrossNox** [comment]
Ok, so my plan is as follows:
- Merge this PR and release a new version, so as to avoid broken pipelines (forcing `docutils <= 0.18` seemed weird in this regard)
- Drop python2 support altogether in a future release. I'll be thinking what the best way to go about that would be.

**Comment by adrien-berchet** [comment]
Hi @CrossNox 
Would it be possible to release a new version as you planned please? As you said, it's a bit annoying to force `docutils <= 0.18` in every repos.
Thanks

**Comment by CrossNox** [comment]
Yep, sorry, had my last final last night. Will work on this later today. Tests were not passing and was not quite as straightforward as I had planned.

**Comment by adrien-berchet** [comment]
Ok, I see, no problem. Thank you very much to work on this :)

**Pull request merged**
